# This is a basic workflow to help you get started with Actions

name: Publish Permission Manager Library

# Event - When should our workflow start. Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to main
        uses: actions/checkout@v4.2.0

      - name: Setup Java JDK 21
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Generate Build with Gradle
        run: ./gradlew build

      - name: Uploading build artifact
        uses: actions/upload-artifact@v4
        with:
          name: azpm.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  # Publish library .aar to maven central
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to main
        uses: actions/checkout@v4.2.0

      - name: Setup Java JDK 21
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Generating Android Artifact .aar file
        run: ./gradlew :pm:assembleRelease

      - name: Uploading .aar artifact
        uses: actions/upload-artifact@v4
        with:
          name: azpm.aar
          path: /Users/apple/Development/Android/PermissionManager/pm/build/outputs/aar/pm-release.aar

      - name: Publish to GitHub packages
        run: ./gradlew :pm:publish
        env:
          GITHUB_USERNAME: ${{ secrets.SECRET_ACTOR }}
          GITHUB_REPOSITORY: ${{ secrets.SECRET_REPOSITORY }}
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}

# This workflow contains a single job called "build"
#  publish:
#    # The type of runner that the job will run on
#    name: Setting up publishing library
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#
#    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - name: Setup Java JDK 21
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'adopt'
#
#      - name: Checking out to branch main
#        uses: actions/checkout@v4
#
#      - name: Cache Gradle and Wrapper
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/.gradle*') }}
#          restore-key: |
#            ${{ runner.os }}-gradle-
#
#      - name: Grant permission for Gradlew to execute
#        run: chmod +x gradlew
#
#      - name: Build AAR
#        run: bash ./gradlew :pm:assemble
#
#      - name: Publish to GitHub Packages
#        run: bash ./gradlew :pm:publish
#        env:
#          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}